# name: Metrics
# on:
#   # Schedule updates (each hour)
#   schedule: [{cron: "0 * * * *"}]
#   workflow_dispatch:
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           token: ${{ secrets.METRICS_TOKEN }}
#           user: ethan-davies
#           template: classic
#           base: header, activity, community, repositories, metadata
#           config_timezone: Europe/London
#           plugin_introduction: yes
#           plugin_introduction_title: yes
#           plugin_notable: yes
#           plugin_notable_from: organization
#           plugin_notable_types: commit

#           plugin_wakatime: yes
#           plugin_wakatime_days: 7
#           plugin_wakatime_limit: 5
#           plugin_wakatime_repositories_visibility: all
#           plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
#           plugin_wakatime_url: https://wakatime.com
#           plugin_wakatime_user: current
#           plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
#           repositories_forks: yes
